package com.email.assistant.app;

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class EmailGenService {
  private static final Logger logger = LoggerFactory.getLogger(EmailGenService.class);
  private final WebClient webClient;
  private final String geminiApiKey;

  public EmailGenService(WebClient.Builder webClientBuilder, GeminiProperties geminiProperties){
    this.geminiApiKey = geminiProperties.getApi().getKey();
    this.webClient=webClientBuilder
    .baseUrl("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent")
    .build();
    logger.info("EmailGenService created successfully!");
    if (geminiApiKey == null || geminiApiKey.isEmpty() || "NOT_FOUND".equals(geminiApiKey)) {
      logger.warn("WARN: Gemini API key is not properly configured!");
    }
  }

  public String generateEmailReply(EmailRequest emailRequest){
    try {
      // Building the prompt
      String prompt=buildPrompt(emailRequest);
      logger.info("Generated prompt for email generation");
      
      // Craft request
      Map<String, Object> requestBody=Map.of(
        "contents",new Object[]{
          Map.of("parts",new Object[]{
            Map.of("text",prompt)
          })
        }
      );

      // Do request and get response
      String response=webClient
      .post()
      .uri("?key="+geminiApiKey)
      .header("Content-Type", "application/json")
      .bodyValue(requestBody)
      .retrieve()
      .bodyToMono(String.class)
      .block();
      
      if (response == null) {
        logger.error("Response is null from API");
        return "Error: No response received from API";
      }
      
      logger.debug("API Response: {}", response);
      
      // Return response
      return extractResponseContent(response);
    } catch (WebClientResponseException e) {
      logger.error("WebClient error: {} - {}", e.getStatusCode(), e.getResponseBodyAsString());
      return "Error: API returned " + e.getStatusCode() + " - " + e.getMessage();
    } catch (Exception e) {
      logger.error("Error generating email reply", e);
      return "Error: " + e.getMessage();
    }
  }

  private String extractResponseContent(String response){
    try {
        ObjectMapper mapper=new ObjectMapper();
        JsonNode rootNode=mapper.readTree(response);
        
        // Check for errors in response
        if (rootNode.has("error")) {
          logger.error("API returned error: {}", rootNode.get("error"));
          return "Error: API error - " + rootNode.path("error").path("message").asText("Unknown error");
        }
        
        JsonNode candidate=rootNode
        .path("candidates")
        .get(0);
        if (candidate == null || candidate.isMissingNode()) {
            logger.error("No candidates found in response");
            return "Error: No response generated by the AI.";
        }
        
        String extractedText = candidate
        .path("content")
        .path("parts")
        .get(0)
        .path("text")
        .asText();
        
        if (extractedText == null || extractedText.isEmpty()) {
          logger.error("Extracted text is empty");
          return "Error: Empty response from AI";
        }
        
        logger.info("Successfully extracted email reply");
        return extractedText;
    } catch (Exception e) {
      logger.error("Error parsing response: {}", response, e);
      return "Error: " + e.getMessage();
    }
  }

  private String buildPrompt(EmailRequest emailRequest){
    StringBuilder prompt=new StringBuilder();
    prompt.append("Generate a professional email reply for the following email content. Please don't generate a subject line ");
    if(emailRequest.getTone()!=null && !emailRequest.getTone().isEmpty()){
      prompt.append("Use a ").append(emailRequest.getTone()).append(" tone.");
    }
    prompt.append("\nOriginal email: \n").append(emailRequest.getEmailContent());
    return prompt.toString();
  }
}